// Bundled, on-device list of UK towns/cities for the coarse-area type-ahead.
// No network, no API key, no keystrokes leaving the device — this is the COARSE
// area shown to others (town/city level), never precise location.
//
// Each place's `slug` is derived deterministically from its canonical `name`, so
// selecting "Cardiff" always stores name "Cardiff" + slug "cardiff" (no
// fragmentation). The slug is the reconciliation key to the slugged `areas`
// table in the Activity Finder phase. Names are unique; coverage is the major
// population centres and is intentionally expandable.

export type UkPlace = { name: string; region: string; slug: string };

export function slugifyPlace(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/['’.]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const RAW: ReadonlyArray<{ name: string; region: string }> = [
  // England
  { name: "London", region: "England" },
  { name: "Birmingham", region: "England" },
  { name: "Manchester", region: "England" },
  { name: "Liverpool", region: "England" },
  { name: "Leeds", region: "England" },
  { name: "Sheffield", region: "England" },
  { name: "Bristol", region: "England" },
  { name: "Newcastle upon Tyne", region: "England" },
  { name: "Nottingham", region: "England" },
  { name: "Leicester", region: "England" },
  { name: "Coventry", region: "England" },
  { name: "Bradford", region: "England" },
  { name: "Stoke-on-Trent", region: "England" },
  { name: "Wolverhampton", region: "England" },
  { name: "Plymouth", region: "England" },
  { name: "Southampton", region: "England" },
  { name: "Portsmouth", region: "England" },
  { name: "Derby", region: "England" },
  { name: "Brighton and Hove", region: "England" },
  { name: "Kingston upon Hull", region: "England" },
  { name: "Preston", region: "England" },
  { name: "Norwich", region: "England" },
  { name: "Reading", region: "England" },
  { name: "Luton", region: "England" },
  { name: "Milton Keynes", region: "England" },
  { name: "Northampton", region: "England" },
  { name: "Bournemouth", region: "England" },
  { name: "Swindon", region: "England" },
  { name: "Ipswich", region: "England" },
  { name: "Oxford", region: "England" },
  { name: "Cambridge", region: "England" },
  { name: "Peterborough", region: "England" },
  { name: "York", region: "England" },
  { name: "Exeter", region: "England" },
  { name: "Gloucester", region: "England" },
  { name: "Cheltenham", region: "England" },
  { name: "Bath", region: "England" },
  { name: "Worcester", region: "England" },
  { name: "Hereford", region: "England" },
  { name: "Lincoln", region: "England" },
  { name: "Chester", region: "England" },
  { name: "Carlisle", region: "England" },
  { name: "Lancaster", region: "England" },
  { name: "Blackpool", region: "England" },
  { name: "Blackburn", region: "England" },
  { name: "Burnley", region: "England" },
  { name: "Bolton", region: "England" },
  { name: "Wigan", region: "England" },
  { name: "Warrington", region: "England" },
  { name: "Salford", region: "England" },
  { name: "Stockport", region: "England" },
  { name: "Oldham", region: "England" },
  { name: "Rochdale", region: "England" },
  { name: "Bury", region: "England" },
  { name: "St Helens", region: "England" },
  { name: "Birkenhead", region: "England" },
  { name: "Southport", region: "England" },
  { name: "Sunderland", region: "England" },
  { name: "Gateshead", region: "England" },
  { name: "South Shields", region: "England" },
  { name: "Durham", region: "England" },
  { name: "Darlington", region: "England" },
  { name: "Hartlepool", region: "England" },
  { name: "Middlesbrough", region: "England" },
  { name: "Stockton-on-Tees", region: "England" },
  { name: "Scarborough", region: "England" },
  { name: "Harrogate", region: "England" },
  { name: "Huddersfield", region: "England" },
  { name: "Halifax", region: "England" },
  { name: "Wakefield", region: "England" },
  { name: "Barnsley", region: "England" },
  { name: "Doncaster", region: "England" },
  { name: "Rotherham", region: "England" },
  { name: "Chesterfield", region: "England" },
  { name: "Mansfield", region: "England" },
  { name: "Telford", region: "England" },
  { name: "Shrewsbury", region: "England" },
  { name: "Stafford", region: "England" },
  { name: "Crewe", region: "England" },
  { name: "Macclesfield", region: "England" },
  { name: "Walsall", region: "England" },
  { name: "West Bromwich", region: "England" },
  { name: "Dudley", region: "England" },
  { name: "Solihull", region: "England" },
  { name: "Sutton Coldfield", region: "England" },
  { name: "Tamworth", region: "England" },
  { name: "Nuneaton", region: "England" },
  { name: "Rugby", region: "England" },
  { name: "Redditch", region: "England" },
  { name: "Kidderminster", region: "England" },
  { name: "Stratford-upon-Avon", region: "England" },
  { name: "Banbury", region: "England" },
  { name: "Bedford", region: "England" },
  { name: "Kettering", region: "England" },
  { name: "Corby", region: "England" },
  { name: "Wellingborough", region: "England" },
  { name: "Colchester", region: "England" },
  { name: "Chelmsford", region: "England" },
  { name: "Southend-on-Sea", region: "England" },
  { name: "Basildon", region: "England" },
  { name: "Harlow", region: "England" },
  { name: "Brentwood", region: "England" },
  { name: "Watford", region: "England" },
  { name: "St Albans", region: "England" },
  { name: "Hemel Hempstead", region: "England" },
  { name: "Stevenage", region: "England" },
  { name: "Welwyn Garden City", region: "England" },
  { name: "Slough", region: "England" },
  { name: "Maidenhead", region: "England" },
  { name: "Bracknell", region: "England" },
  { name: "High Wycombe", region: "England" },
  { name: "Aylesbury", region: "England" },
  { name: "Basingstoke", region: "England" },
  { name: "Winchester", region: "England" },
  { name: "Eastleigh", region: "England" },
  { name: "Fareham", region: "England" },
  { name: "Gosport", region: "England" },
  { name: "Havant", region: "England" },
  { name: "Aldershot", region: "England" },
  { name: "Farnborough", region: "England" },
  { name: "Andover", region: "England" },
  { name: "Salisbury", region: "England" },
  { name: "Guildford", region: "England" },
  { name: "Woking", region: "England" },
  { name: "Camberley", region: "England" },
  { name: "Epsom", region: "England" },
  { name: "Redhill", region: "England" },
  { name: "Crawley", region: "England" },
  { name: "Horsham", region: "England" },
  { name: "Worthing", region: "England" },
  { name: "Bognor Regis", region: "England" },
  { name: "Chichester", region: "England" },
  { name: "Eastbourne", region: "England" },
  { name: "Hastings", region: "England" },
  { name: "Bexhill-on-Sea", region: "England" },
  { name: "Maidstone", region: "England" },
  { name: "Chatham", region: "England" },
  { name: "Gillingham", region: "England" },
  { name: "Dartford", region: "England" },
  { name: "Gravesend", region: "England" },
  { name: "Canterbury", region: "England" },
  { name: "Margate", region: "England" },
  { name: "Folkestone", region: "England" },
  { name: "Dover", region: "England" },
  { name: "Ashford", region: "England" },
  { name: "Royal Tunbridge Wells", region: "England" },
  { name: "Tonbridge", region: "England" },
  { name: "Weston-super-Mare", region: "England" },
  { name: "Taunton", region: "England" },
  { name: "Bridgwater", region: "England" },
  { name: "Yeovil", region: "England" },
  { name: "Weymouth", region: "England" },
  { name: "Poole", region: "England" },
  { name: "Torquay", region: "England" },
  { name: "Paignton", region: "England" },
  { name: "Newton Abbot", region: "England" },
  { name: "Truro", region: "England" },
  { name: "Penzance", region: "England" },
  { name: "Falmouth", region: "England" },
  { name: "Newquay", region: "England" },
  { name: "Barnstaple", region: "England" },
  { name: "Trowbridge", region: "England" },
  { name: "Chippenham", region: "England" },
  { name: "Stroud", region: "England" },
  { name: "Cirencester", region: "England" },
  { name: "Grimsby", region: "England" },
  { name: "Scunthorpe", region: "England" },
  { name: "Boston", region: "England" },
  { name: "King's Lynn", region: "England" },
  { name: "Great Yarmouth", region: "England" },
  { name: "Lowestoft", region: "England" },
  { name: "Bury St Edmunds", region: "England" },
  { name: "Ely", region: "England" },
  { name: "Huntingdon", region: "England" },
  // Scotland
  { name: "Glasgow", region: "Scotland" },
  { name: "Edinburgh", region: "Scotland" },
  { name: "Aberdeen", region: "Scotland" },
  { name: "Dundee", region: "Scotland" },
  { name: "Inverness", region: "Scotland" },
  { name: "Perth", region: "Scotland" },
  { name: "Stirling", region: "Scotland" },
  { name: "Paisley", region: "Scotland" },
  { name: "East Kilbride", region: "Scotland" },
  { name: "Livingston", region: "Scotland" },
  { name: "Hamilton", region: "Scotland" },
  { name: "Cumbernauld", region: "Scotland" },
  { name: "Kirkcaldy", region: "Scotland" },
  { name: "Dunfermline", region: "Scotland" },
  { name: "Ayr", region: "Scotland" },
  { name: "Kilmarnock", region: "Scotland" },
  { name: "Greenock", region: "Scotland" },
  { name: "Coatbridge", region: "Scotland" },
  { name: "Glenrothes", region: "Scotland" },
  { name: "Airdrie", region: "Scotland" },
  { name: "Falkirk", region: "Scotland" },
  { name: "Irvine", region: "Scotland" },
  { name: "Dumfries", region: "Scotland" },
  { name: "Motherwell", region: "Scotland" },
  { name: "Elgin", region: "Scotland" },
  { name: "Fort William", region: "Scotland" },
  { name: "Oban", region: "Scotland" },
  { name: "St Andrews", region: "Scotland" },
  // Wales
  { name: "Cardiff", region: "Wales" },
  { name: "Swansea", region: "Wales" },
  { name: "Newport", region: "Wales" },
  { name: "Wrexham", region: "Wales" },
  { name: "Barry", region: "Wales" },
  { name: "Caerphilly", region: "Wales" },
  { name: "Bridgend", region: "Wales" },
  { name: "Neath", region: "Wales" },
  { name: "Port Talbot", region: "Wales" },
  { name: "Cwmbran", region: "Wales" },
  { name: "Llanelli", region: "Wales" },
  { name: "Merthyr Tydfil", region: "Wales" },
  { name: "Pontypridd", region: "Wales" },
  { name: "Aberdare", region: "Wales" },
  { name: "Bangor", region: "Wales" },
  { name: "Llandudno", region: "Wales" },
  { name: "Colwyn Bay", region: "Wales" },
  { name: "Rhyl", region: "Wales" },
  { name: "Prestatyn", region: "Wales" },
  { name: "Aberystwyth", region: "Wales" },
  { name: "Carmarthen", region: "Wales" },
  { name: "Haverfordwest", region: "Wales" },
  { name: "Brecon", region: "Wales" },
  { name: "Monmouth", region: "Wales" },
  // Northern Ireland
  { name: "Belfast", region: "Northern Ireland" },
  { name: "Derry", region: "Northern Ireland" },
  { name: "Lisburn", region: "Northern Ireland" },
  { name: "Newtownabbey", region: "Northern Ireland" },
  { name: "Craigavon", region: "Northern Ireland" },
  { name: "Ballymena", region: "Northern Ireland" },
  { name: "Newtownards", region: "Northern Ireland" },
  { name: "Carrickfergus", region: "Northern Ireland" },
  { name: "Coleraine", region: "Northern Ireland" },
  { name: "Antrim", region: "Northern Ireland" },
  { name: "Omagh", region: "Northern Ireland" },
  { name: "Larne", region: "Northern Ireland" },
  { name: "Armagh", region: "Northern Ireland" },
  { name: "Enniskillen", region: "Northern Ireland" },
  { name: "Newry", region: "Northern Ireland" },
];

export const UK_PLACES: UkPlace[] = RAW.map((p) => ({ ...p, slug: slugifyPlace(p.name) }));

function normalize(s: string): string {
  return s
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "");
}

/** On-device search: prefix matches first, then substring, capped at `limit`. */
export function searchPlaces(query: string, limit = 8): UkPlace[] {
  const q = normalize(query);
  if (!q) return [];
  const starts: UkPlace[] = [];
  const contains: UkPlace[] = [];
  for (const place of UK_PLACES) {
    const n = normalize(place.name);
    if (n.startsWith(q)) starts.push(place);
    else if (n.includes(q)) contains.push(place);
  }
  return [...starts, ...contains].slice(0, limit);
}
